### ISSUE TITLE
Global Hamcrest matchers unit tests cause Behat conflicts

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-fulltextsearch#112]
The issue is more completely described here: https://gitlab.cwp.govt.nz/cwp/cwp-installer/issues/3 but is basically that when Hamcrest is setup as global (default) then global method name conflicts arise when other code needs to use same-named methods. In the present case, you cannot run a Behat test suite with these set as global.

The fix is to simply pass `false` to `Phockito::include_hamcrest()` in the test classes that call it.

Applying this fix and running the module's tests, results in most still passing, except for `SolrIndexTest` which would be fixed by declaring all methods as public statics in `Hamcrest.php` within a class, and then calling `Hamcrest::anything()` or similar. (This after ~11s consideration)

**Comment by tractorcow** [comment]
I'll attempt to include this in my upcoming fix for https://github.com/silverstripe-labs/silverstripe-fulltextsearch/issues/107

**Comment by tractorcow** [comment]
They are already false for all places that invoke it. :D

**Comment by dhensby** [comment]
@tractorcow is this fixed?

**Comment by tractorcow** [comment]
Yep
