### ISSUE TITLE
Can the Webdav port be different from the Solr port?

### ISSUE THREAD

**Issue by Lightnicus** [silverstripe/silverstripe-fulltextsearch#125]
At the moment I can not find a way to use a different port for webdav than used for Solr (defaulting to 8983). 
In some configuration cases that port is different.
I can write my own SolrConfigStore class as a workaround from the looks of it.

Wonder if there  can be an optional config value inside indexstore config for the port for more flexibility?

**Comment by tractorcow** [comment]
You could update SolrConfigStore_WebDAV so that it checked for `$config['webdavport']` before falling back to `$config['port']` if you wanted. You'd need to make a core change though.

**Comment by dhensby** [comment]
PR please

**Comment by Lightnicus** [comment]
PR coming up! you guys are quick :-)

**Comment by robbieaverill** [comment]
Thanks @Lightnicus - fixed in #126
