### ISSUE TITLE
Solr_Configure needs more verbosity!

### ISSUE THREAD

**Issue by jakedaleweb** [silverstripe/silverstripe-fulltextsearch#133]
As part of some user feedback from CWP regarding solr we have found that agencies feel there is a lack of error reporting with regards to a Solr_Configure. I believe one can make this a bit more verbose with a `?Verbose=1` currently, but I may be wrong.

Anyway, it would be good to see any errors that occur on a Solr_Configure by default and maybe a nice success message if there are none.
(see HD16473 for more info)

**Comment by robbieaverill** [comment]
@jakedaleweb would you mind posting a sanitised copy of HD16473 here for reference?

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
