### ISSUE TITLE
Archived and Unpublished pages do not remove 'Live' variant from index

### ISSUE THREAD

**Issue by DarrenInwood** [silverstripe/silverstripe-fulltextsearch#134]
To replicate:

Create a new page and save it as draft.
Search for the page (in incognito mode) - 0 results.

Publish the page.
Search for the page - 1 result.

Unpublish the page.
Search for the page.
Expected - 0 results.
Actual - PaginatedList reports total size of 1, but is empty.

Publish the page, then Archive it.
Search for the page.
Expected - 0 results.
Actual - PaginatedList reports total size of 1, but is empty.

Versioned alters this query so that we only get the item if it has a live version; the item is being returned from the index still, but is not being added to the list.
https://github.com/silverstripe/silverstripe-fulltextsearch/blob/master/code/solr/SolrIndex.php#L749

However, the total including the ones filtered out is being set as the PaginatedList total:
https://github.com/silverstripe/silverstripe-fulltextsearch/blob/master/code/solr/SolrIndex.php#L786

As a workaround I add these lines to affected DataObjects.

`
    public function onBeforeDelete()
    {
        $this->LastEdited = time();
        $this->write();
    }

    public function onAfterUnpublish()
    {
        singleton('nameofyourindex')->delete(
            ClassInfo::baseDataClass($this->ClassName),
            $this->ID,
            array (
              'SearchVariantVersioned' => 'Live',
              'SearchVariantSubsites' => '0',
            )
        );
    }
`

**Comment by tractorcow** [comment]
Ok, proper fix at https://github.com/silverstripe/silverstripe-fulltextsearch/pull/138
