### ISSUE TITLE
UNLOAD a core once its renamed

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-fulltextsearch#15]
Solr_Configure indirectly writes solr.xml through an API request, adding new cores and reloading as required.
If the class name of an index changes, the old core entry isn't removed from solr.xml.
SilverStripe can't detect renames as such, but can diff existing cores vs. new ones. 
See http://wiki.apache.org/solr/CoreAdmin

That's assuming SilverStripe is the only client using Solr cores, which is highly likely.
In the unlikely case there's another client creating its own cores, we could pass in a merge=true parameter
to the Solr_Configure task?

**Comment by dhensby** [comment]
This issue hasn't had any reaction or feedback in 5 years; I'd be highly cautious about unloading cores just because we don't manage them via the SS application (we don't do that with relational databases)...

I'd only accept this as an idea if deleting the other cores was opt-in...

Unless there's someone who wants to take ownership of this, I think this issue should be closed.

**Comment by dhensby** [comment]
> Dan, do you know if an old core keeps using resources? For example, renaming a core with a large index keeps the old index in place, while the new core builds up a new index. So you might consider this a bug rather than an enhancement in an operational context. Do we even know how many "ghost cores" we have in CWP?

I have no idea about any of this ;)

But I still think deleting cores is dangerous!

**Comment by chillu** [comment]
Cores are stateless, right? They can be reconstructed from `solrconfig.xml` and a reindex. So it's no dangerous than a `Solr_Configure` and `Solr_Reindex`.

**Comment by dhensby** [comment]
That's true, but my point is less CWP focused and more generic; deleting cores just because our application doesn't know about them is a bit risky.

Just like deleting a DB because it's not the primary one registered with our application would be bold.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
