### ISSUE TITLE
v2.3.1: $dirty_indexes incorrect default property value

### ISSUE THREAD

**Issue by chrispenny** [silverstripe/silverstripe-fulltextsearch#151]
Fix:
https://github.com/silverstripe/silverstripe-fulltextsearch/pull/148

Currently in `SearchUpdateCommitJobProcessor`:
```php
/**
 * List of dirty indexes to be committed
 *
 * @var array
 */
public static $dirty_indexes = true;
```

This results in many Warning being thrown as `$dirty_indexes` is used (from what I could see) exclusively as type `array`, not `boolean`.

EG:
```
#0 in_array() expects parameter 2 to be array, boolean given:: called at [/sites/statsunleashed/releases/20170811014625/fulltextsearch/code/search/processors/SearchUpdateCommitJobProcessor.php:217]
```

**Comment by robbieaverill** [comment]
I feel like someone would've had a reason make this default to true, but nevertheless it's incorrect and should be fixed

**Comment by NightJar** [comment]
Novice question: Why is it public?

**Comment by robbieaverill** [comment]
Probably a hangover from previous SilverStripe versions, it should be private now

**Comment by chrispenny** [comment]
I will update this in my PR now.

**Comment by chrispenny** [comment]
It looks like this is currently being accessed from outside the class:
`BatchedProcessorTest` line 92:
```
SearchUpdateCommitJobProcessor::$dirty_indexes = array();
```

In the interest of keeping this Pull Request simple (because this issue currently generates 1,600 warning per day for one of our sites), hopefully everyone is ok with me leaving the visibility as `public` and addressing this separately.

**Comment by robbieaverill** [comment]
Yeah, that's fine - leave as is. We can move this to a state object in SS4 at some point.
