### ISSUE TITLE
Remove unused SapphireTest::is_running_test check and any other references to it

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-fulltextsearch#163]
The test suite at the moment is passing without throwing this exception: https://github.com/silverstripe/silverstripe-fulltextsearch/pull/141#discussion_r151013129

The fact that it's not being executed at the moment is not having an adverse effect on the test suite, so we should just remove this instead.

Also check for other references to `is_running_test` in the code and remove as necessary.

**Comment by raissanorth** [comment]
SapphireTest::is_running_test is not referenced anywhere else.

**Comment by robbieaverill** [comment]
Thanks!
