### ISSUE TITLE
Lose refs to silverstripe/fulltextsearch-localsolr

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-fulltextsearch#193]
Mainly in composer.json, possibly elsewhere too.

**Comment by robbieaverill** [comment]
Do you think it's not useful to suggest it, e.g. in composer.json?

**Comment by phptek** [comment]
No, it's not been committed-to in 4 years and exists in the silverstripe-archive. I'm figuring therefore it's deprecated right?

**Comment by robbieaverill** [comment]
Yeah you might be right. Personally, I still use it regularly for local testing

**Comment by phptek** [comment]
Does it still work with SS4?

**Comment by robbieaverill** [comment]
Yep, I just cloned it in because the constraint needs loosening. https://github.com/silverstripe-archive/silverstripe-fulltextsearch-localsolr/pull/6

**Comment by phptek** [comment]
Hmmm prob irrelevant really, there's no PHP code in there!

**Comment by robbieaverill** [comment]
I think we should keep it in the docs for local testing. Feel free to reopen if you strongly disagree =)
