### ISSUE TITLE
System sake commands will not execute on SSP

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-fulltextsearch#197]
`SolrReindexImmediateHandler::processGroup` runs a system command to run a Solr index immediately, however on SSP the shimmed environment variables don't transfer through to this command so it results in a "SilverStripe Framework requires database configuration defined via .env" or similar message:

```php
        $frameworkPath = ModuleLoader::getModule('silverstripe/framework')->getPath();
        $scriptPath = sprintf("%s%scli-script.php", $frameworkPath, DIRECTORY_SEPARATOR);
        $scriptTask = "php {$scriptPath} dev/tasks/{$taskName}";

        $cmd = "{$scriptTask} index={$indexClassEscaped} class={$class} group={$group} groups={$groups} variantstate={$statevar}";
        $cmd .= " verbose=1 2>&1";
        $logger->info("Running '$cmd'");

        // Execute script via shell
        $res = $logger ? passthru($cmd) : `$cmd`;
```

We should remove this and replace it with loading and executing the required task class instead. Ideally we'd replace the `$taskName` argument passes into `->triggerReindex()` with the instance of the task instead, so the immediate handler can simply call `$task->run($request)` after setting the requires data into the request object.

cc @silverstripe/core-team for thoughts on making this change

cc @elliot-sawyer @silverstripe-elliot @jakedaleweb

**Comment by tractorcow** [comment]
> We should remove this and replace it with loading and executing the required task class instead. Ideally we'd replace the $taskName argument passes into ->triggerReindex() with the instance of the task instead, so the immediate handler can simply call $task->run($request) after setting the requires data into the request object.

This will cause performance issues with all the memory consumption being forced into a single process.

What is causing sake to not work on platform? I'd be more interested in fixing that instead.

**Comment by silverstripe-elliot** [comment]
Does this impact on the QueuedJob as well?

**Comment by tractorcow** [comment]
It probably will, with doorman.

**Comment by robbieaverill** [comment]
>This will cause performance issues with all the memory consumption being forced into a single process.

Would that be any different from how it current executes?

>What is causing sake to not work on platform? I'd be more interested in fixing that instead.

Environment variables are shiv'd into the CLI environment somehow. I'm not 100% sure, but there's no .env file available.

**Comment by tractorcow** [comment]
My opinion in shift to using symfony/process and use the env inheritance option it provides.

**Comment by robbieaverill** [comment]
Quick discussion with @NightJar and @tractorcow:

Use symfony/process to handle the system command rather than replacing it with direct PHP class execution.

In SS3 this logic would've worked because there's always an \_ss_environment.php file available for the child process to read on its own. In SS4 the equivalent is .env, but in SSP we won't have one. The environment variables shivved in from apache are not available to child CLI processes that are spawned from apache via exec calls etc.

Use symfony/process component, and ensure it inherits env vars from the current process `$process->inheritEnvironmentVariables()` (see silverstripe/cow).

This approach would mean we don't need to modify the handler interface, and can just modify the immediate handler on its own to use a symfony process instead of direct system exec calls.

Spellcheck module may be doing similar command line calls to the hunspell binary, so we potentially have another use case for adding an additional dependency.

**Comment by andrewandante** [comment]
For context on SSP - if you want to run something via CLI, you need to use:

```
vhost={$vhost} /usr/local/bin/sushi dev/tasks/{$taskName}
```

As that script loads the environment variables in to the CLI runner.

> Does this impact on the QueuedJob as well?

The queuedjobs cron is run on SSP via the `sushi` script, so the env vars make it in.

Regardless, I think moving it to a symfony process is a great idea 👍

**Comment by sminnee** [comment]
I think with SilverStripe 4 the expectation should be that any subprocess created will need to have environment variables of any source passed through in order to preserve correct functioning, e.g. this:

> Use symfony/process component, and ensure it inherits env vars from the current process $process->inheritEnvironmentVariables() (see silverstripe/cow).

Potentially the use of this for child process creation needs to be recommended in the SS4 docs?

**Comment by robbieaverill** [comment]
Yeah 100%, provided this solution works =)
