### ISSUE TITLE
dev/tasks/Solr_Reconfigure fails - can't find Index class.

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-fulltextsearch#198]
Probably an edge case, however have just noted (and been able to side-step for now) the following issue:
No matter where an index is defined (e.g. module provided such as in `cwp/cwp-search` or custom classes), performing a reconfigure will result in an Injector Reflection Exception: Cannot find class `Vendor\Module\Some\NameSpace\ThatSolrIndex`.

e.g. `Running Task SilverStripe\FullTextSearch\Solr\Tasks\Solr_Reindex ERROR [Emergency]: Uncaught SilverStripe\Core\Injector\InjectorNotFoundException: exception 'ReflectionException' with message 'Class TractorCow\\Fluent\\Search\\FluentSolrIndex does not exist'`
Although I have also seen this with `CWPSolrIndex` and `ElementalSolrIndex`.

This could be an edge case as I'm developing locally (with `silverstripe/fulltextsearch-localsolr`) on Windows - `php-5.6.31-Win32-VC11-x86`.

Having had a though while typing this out, this _could_ be related to the double backslash in the class name it's looking for. I'd probably start looking there :)

**Comment by robbieaverill** [comment]
@NightJar fixed by #203 ?

**Comment by NightJar** [comment]
Oh, yep sorry forgot to link!
