### ISSUE TITLE
Remove redundant code

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-fulltextsearch#199]
https://github.com/silverstripe/silverstripe-fulltextsearch/blob/436b7663e12bd8744ee78313b789496a95fa53cf/src/Search/Variants/SearchVariantVersioned.php#L58

I'm not sure how this undefined var isn't causing a `Fatal Error` - so far as I can tell this renders FulltextSearch unusable out of the box, at current :/
Or am I confusing my syntax? brain fried, plz send help.

**Comment by robbieaverill** [comment]
It's defined in SearchQuery, line 15

**Comment by NightJar** [comment]
Brain fried ✔️

PHP differentiates:
`SomeClass::$thing` is a _static variable_ lookup,
`SomeClass::thing` is a _CONSTANT_ lookup,

`SomeClass->thing` is a member variable lookup,
`SomeClass->$thing` is a dynamic "name of the member variable is in this current scope variable" lookup.
