### ISSUE TITLE
Update to use proxied DB instead of self-proxied

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-fulltextsearch#201]
Written up a proxy module at https://github.com/tractorcow/silverstripe-proxy-db. This allows registration of a shared proxy database that multiple modules can decorate.

Also see:
 - https://github.com/lekoala/silverstripe-debugbar/issues/93
 - https://github.com/silverstripe/silverstripe-auditor/issues/16

**Comment by robbieaverill** [comment]
It's worth noting that this change would be required to get this module into the CWP 2.0 recipe, since at the moment it conflicts with 2 or 3 other SilverStripe modules with also proxy the database.
