### ISSUE TITLE
Need ability to disable fulltextsearch

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-fulltextsearch#209]
In cases where during development, a solr instance may not currently be running. It's necessary to allow the fulltextsearch module to self-disable in certain cases, either via yml config or an environment variable, so it does not cause system failures.

**Comment by robbieaverill** [comment]
I think it's worth noting that this only happens with CWP, since cwp/cwp-search calls `CwpSolr::configure();` in \_config.php

**Comment by robbieaverill** [comment]
PR at #210
