### ISSUE TITLE
Search field empty error message when valid term entered

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-fulltextsearch#211]
When using the CWP installer 1.8.0 and 1.8.1 the following error message is displayed, even though a valid search term has been entered.

![image](https://user-images.githubusercontent.com/14869519/38277228-ca72379c-37eb-11e8-8cc5-81299d4e00a0.png)

I use the following versions:
```
silverstripe/fulltextsearch               2.4.0             
silverstripe/fulltextsearch-localsolr     dev-master 0c6571c
silverstripe/framework                    3.6.5
monolog/monolog                           1.23.0   
```

The issue appears to be resolved in CWP2.0-rc1 (using the versions below), where the full text search functions as expected. 
```
silverstripe/fulltextsearch               dev-master bd01a56
silverstripe/fulltextsearch-localsolr     dev-master 0c6571c
silverstripe/framework                    4.1.x-dev
monolog/monolog                           1.23.0
ptcinc/solr-php-client                    v1.0.0
symfony/process                           v3.4.6
tractorcow/silverstripe-proxy-db          0.1.0
```

**Comment by robbieaverill** [comment]
I can't reproduce this, did you run the Solr_Configure and Solr_Reindex tasks?

**Comment by raissanorth** [comment]
I had run both tasks at the time and Dylan reproduced this too. However, I have tested it again and it is no longer an issue, yeah! Assuming that recent changes I pulled in fixed this, I am closing this issue.
