### ISSUE TITLE
Multi-word synonym support

### ISSUE THREAD

**Issue by timkung** [silverstripe/silverstripe-fulltextsearch#213]
Currently, it is extremely difficult to get multi-word synonyms (e.g. acronyms) working.

There are numerous articles that describe how it can be achieved, but often require overly complex queries being built up, custom Solr analyzers being added or a lot of edge cases not being accounted for/having to live with in order to have that feature.

To help solve this, Solr have implemented a SynonymGraphFilter but this is only available in Solr 6.6.

So not actually specific to this module itself (other than the default supported Solr versions), but creating this issue to highlight a limitation.

Good reference article: https://lucidworks.com/2017/04/18/multi-word-synonyms-solr-adds-query-time-support/

**Comment by robbieaverill** [comment]
I've labelled this as a major change for now since it sounds like it would involve updating the Solr engine

**Comment by GuySartorelli** [comment]
This is no longer a supported module and we are unlikely to implement this. I recommend using an alternative like https://github.com/Firesphere/silverstripe-solr-search instead.
