### ISSUE TITLE
Reindex task removes all indexed content but doesn't replace it with new content.

### ISSUE THREAD

**Issue by cam-findlay** [silverstripe/silverstripe-fulltextsearch#22]
I find that when I have Solr setup and run the Reindex it removes all content from the Solr core but does not replace it with new content from my Pages/DataObjects.

If I save/publish within the CMS the content is however indexed.

Is this how it is intended or is there a problem with the Reindex task?

**Comment by robbieaverill** [comment]
I'm going to assume this has been resolved since 2013. If this is still affecting anybody on more recent versions of SS and FTS please feel free to reopen 😄
