### ISSUE TITLE
Incorrectly configured Solr causes uncaught exception fatal errors

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-fulltextsearch#222]
Currently when attempting to add new CMS pages, or when trying to save existing CMS pages with incorrectly configured Solr you will get uncaught exceptions causing fatal errors. For example:

![image](https://user-images.githubusercontent.com/3260989/41952979-1533da38-7a27-11e8-951d-6b6687809514.png)

In SS3 this was not an issue.

**Comment by robbieaverill** [comment]
Noting that we added some config to allow devs to disable this: https://github.com/silverstripe/silverstripe-fulltextsearch/pull/210

It'd be nice if it didn't munch up the CMS by default when you don't have Solr running or configured though.

**Comment by ScopeyNZ** [comment]
I addressed this somewhat in #223 but the problem is still there as SilverStripe outputs errors logged above the "info" level. This is especially a problem for JSON responses with Ajax (like saving CMS pages). Should we reduce the log level or wait for something in silverstripe/framework?

**Comment by robbieaverill** [comment]
We should reduce the log level for now to one that won't be caught up in the core logger
