### ISSUE TITLE
ContentControllerExtension not used in 3.4.0

### ISSUE THREAD

**Issue by thats4shaw** [silverstripe/silverstripe-fulltextsearch#231]
I've noticed in 3.4.0 that `SilverStripe\FullTextSearch\Solr\Control\ContentControllerExtension` is no longer used.

Stumbled across with this coming from 3.3.1. 

Initially added in 7b78a841b015e1baa5f86404c0d88e81256dbf77 and removed in e08731d1f1b783f8202f283d85bdb4d5d4d8b720 which is included in the 3.4.0 tag.

I notice there is a related TODO mentioning to update docs once #216 was merged so perhaps it was forgotten about.

**Comment by robbieaverill** [comment]
Thanks for raising this issue @thats4shaw. I haven't looked into this at all, but do you think that this extension is dead code, or missing functionality that should be restored by default?

**Comment by robbieaverill** [comment]
Fancy a PR @thats4shaw? =)

**Comment by thats4shaw** [comment]
PR added @robbieaverill 👍.
