### ISSUE TITLE
Incorrect docs on ShowInSearch

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-fulltextsearch#237]
https://github.com/silverstripe/silverstripe-fulltextsearch/blob/65b780f629ec31168902217d734079a14727896f/docs/en/03_configuration.md#adding-dataobjects says:

> getShowInSearch() is required to get the record to show in search, since all results are filtered by ShowInSearch.

There's no functionality in the module to make this work. It's part of the CWP module. We should either document this as a recipe to implement in your search index, or (my preference) actually implement it in the default search index definitions we mention to developers.

See CWP implementation:

https://github.com/silverstripe/cwp-search/blob/057c873e8de4713b22ee72077bfe7ed41b0879cc/src/Solr/CwpSolrIndex.php#L27

## PR
Extract from PR (merged):
https://github.com/silverstripe/silverstripe-fulltextsearch/pull/275/files#diff-1959cad5d7c9eed2e0117a24d3f4da7eR175

**Comment by brynwhyman** [comment]
We should run this one past some of our internal teams to assert what impact this might have on existing implementations.

**Comment by chillu** [comment]
> We should run this one past some of our internal teams to assert what impact this might have on existing implementations.

I've flagged this for SAs and PDs today: https://silverstripeltd.slack.com/archives/C052GD0J0/p1584589306051700

**Comment by emteknetnz** [comment]
Have updated docs
https://github.com/silverstripe/silverstripe-fulltextsearch/pull/275/files#diff-1959cad5d7c9eed2e0117a24d3f4da7eR150

**Comment by Cheddam** [comment]
Resolved in #275.
