### ISSUE TITLE
SearchVariant::withCommon expects classes in an array indexed by class names

### ISSUE THREAD

**Issue by michalkleiner** [silverstripe/silverstripe-fulltextsearch#241]
The newly introduced SearchVariant::withCommon method expects a list of classes in an array indexed by class names, which breaks the previously functioning behaviour with just numeric keys. The class is already expected in the 'class' option anyway, so it's an unnecessary duplication.

**Comment by NightJar** [comment]
PR @ #242

**Comment by michalkleiner** [comment]
PR #242 merged, thanks @NightJar
