### ISSUE TITLE
Incorrect command in Quickstart docs

### ISSUE THREAD

**Issue by SiWhite** [silverstripe/silverstripe-fulltextsearch#244]
The docs say to run the following command:

`composer require silverstripe/fulltextsearch && vendor/bin/fts_quickstart`

This results in the message: 'no such file or directory: vendor/bin/fts_quickstart'

Looking in the 'vendor/bin' folder shows the file is named 'fulltextsearch_quickstart'. This should be updated in the docs. Thanks.

**Comment by robbieaverill** [comment]
Yeah you're right! Would you like to make a PR to update the docs?

**Comment by SiWhite** [comment]
> Yeah you're right! Would you like to make a PR to update the docs?

Yes, I think I have done it now - my first PR! :)

**Comment by robbieaverill** [comment]
Fixed in #245 - thanks @SiWhite!
