### ISSUE TITLE
Can't search for words that have an hyphen in it

### ISSUE THREAD

**Issue by am071092** [silverstripe/silverstripe-fulltextsearch#254]
If I search for "abc", I would like the search to match words that have a dash in it eg search results include "a-bc", "ab-c".
Is this possible with solr?

**Comment by robbieaverill** [comment]
This is probably related to #253

**Comment by Firesphere** [comment]
This _is_ possible with Solr, but it's a global setting around different factories that split. You can achieve this with your own `types.ss` file possibly.

You could check the Solr documentation on how to achieve this, as I have no example at hand right now.

Most commonly, these are word-delimiter factories that Solr uses.

The Solr4 reference guide isn't online anymore, but you could check the PDF
https://lucene.apache.org/solr/resources.html

**Comment by robbieaverill** [comment]
Thanks for the response @Firesphere, useful!

I'm going to close this and consolidate it into #253
