### ISSUE TITLE
Module is utterly out of date

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-fulltextsearch#268]
This module is stuck in Solr 4, which is well end of life. This module is being maintained for no proper reason besides legacy.

Using this module should be discouraged. Given it relies on old and outdated protocols and software, this module should have been disabled long ago.

This module relies on an outdated, and not maintained, version of Solr
This module relies on an outdated, and not maintained version of Solr_HTTP_Transport
This module relies on a lot of copy-pasting for the most basic of tasks

This module is outdated and only gives developers and users alike, more pain than use.

**Comment by Firesphere** [comment]
Yes, I have this screenshotted, because I know you will delete it without any feedback or acknowledge any improvements.

**Comment by maxime-rainville** [comment]
I agree, but we sadly we don't have a better solution in the short term. Until we're in a position to provide a better alternative for CWP and SSP customers, we're stuck supporting this module.

I'll close this for now as there's nothing we can do to action this issue.

**Comment by Firesphere** [comment]
There are actually a lot of things you can do, including, but not limited to, either adding support for newer Solr versions and gradually upgrade clients with their consent, and looking at alternatives, that support both older and newer versions of Solr, without breaking.

I can not re-open this issue, but I wholeheartedly disagree with your standpoint.

**Comment by chillu** [comment]
Thanks for working on https://github.com/Firesphere/silverstripe-solr-search Simon :) With hundreds of existing (and often complex) use cases, it's unfortunately more complicated to get from A to B than declaring a module as "utterly out of date". That's definitely true, and we need to do better to provide a transition path (both on a module and platform level). It's a work in progress, I'm spending many days sorting through all the moving parts of "search in SilverStripe" at the moment.
