### ISSUE TITLE
Variant state not reset during processing.

### ISSUE THREAD

**Issue by brettt89** [silverstripe/silverstripe-fulltextsearch#270]
The `SolrReindexBase` class groups changes by Variants and processes them in batches. These Variants (E.g. StageVariant, SubsiteVariant, etc) are used to ensure content is only indexed against a specific state. (E.g. Live content on Subsite 3).

`SolrReindexBase` sets the state accordingly when processing, however it does not reset you back to your original state.

https://github.com/silverstripe/silverstripe-fulltextsearch/blob/afc6364d22d2d2f7d811d791b0bfdb24c677930f/src/Solr/Reindex/Handlers/SolrReindexBase.php#L171

This causes issues when you have mutliple indexes that uses different Variants as the current state is not reset causing the Variants to also be applied to the next set of changes (unless it is specifically overriden).

E.g.

Index1 = (VariantStage + VariantSubsite)
Index2 = (VariantStage)

Once Index1 has finished processing, it does not reset the Subsite state, causing Index2 to also apply the VariantSubsite that was last used (E.g. the last SubsiteID that was processed).

PR for fix raised - #271

**Comment by brettt89** [comment]
For anyone looking for a temporary resolution until this is merged, you can change the order of your defined indexes to ensure those with the lowest common denominator are processed first.

E.g.

```
SilverStripe\FullTextSearch\Search\FullTextSearch:
  indexes:
    - SearchIndex2 (VariantStage)
    - SearchIndex1 (VariantStage + VariantSubsite)
```

This will ensure SearchIndex2 gets processed before the VariantSubsite one is applied. This may not work for all scenarios (E.g. if both have unique variants).

**Comment by robbieaverill** [comment]
Merged, thanks Brett!

**Comment by torleif** [comment]
I've updated our fulltext-search to 3.7, and this issue has started occurring with our results. All pages in our main subsite have a random SubsiteID.
