### ISSUE TITLE
Solr now at version 8

### ISSUE THREAD

**Issue by KiwiMorpheus** [silverstripe/silverstripe-fulltextsearch#296]
Any plans to update or fork to support Solr v8. Solr 4 has had no updates in 6 years.... time to move on??

**Comment by brynwhyman** [comment]
Hi @KiwiMorpheus there's currently no plans from the maintainers of this module to update it to support later versions of Solr.   

If you're looking for Solr 8 support for Silverstripe projects I'd recommend checking out the following module: https://github.com/Firesphere/silverstripe-solr-search 🙂
