### ISSUE TITLE
Migrate to new Symfony cache classes

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-fulltextsearch#302]
```Exception: HTML Parse Error: The "Symfony\Component\Cache\Simple\PhpFilesCache" class is deprecated since Symfony 4.3, use "Symfony\Component\Cache\Adapter\PhpFilesAdapter" and type-hint for "Symfony\Contracts\Cache\CacheInterface" instead. in /sites/cmstest-uat/releases/20211213214917/vendor/silverstripe/fulltextsearch/src/Search/Indexes/SearchIndex.php:502 Stack trace: #0 [internal function]: SilverStripe\FullTextSearch\Search\Indexes\SearchIndex->SilverStripe\FullTextSearch\Search\Indexes\{closure}(16384, 'The "Symfony\\Co...', '/sites/cmstest-...', 20, Array)```

Saw warning on queuedjob message when manually running solr reindex job

I think it's blocking the indexing of content block content on AWS, possibly only when running PHP 8.0

## Acceptance criteria
- [ ] Warnings are visible in the output with failing the indexing tasks
- [ ] The deprecated Symfony API is not used anymore
- [ ] No module reference the old cache implementation
- [ ] All modules that require symphony/cache, are constrained to using the relevant version of Symphony and the kitchen sink is installable.
- [ ] The Fulltext Search cache still works.

### PRs
- [x] https://github.com/silverstripe/silverstripe-fulltextsearch/pull/303
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/10187
- [ ] https://github.com/silverstripe/silverstripe-versioned/pull/349

**Comment by emteknetnz** [comment]
Error comes from

*PhpFilesCache.php*

```
namespace Symfony\Component\Cache\Simple;
...
`@trigger_error(sprintf('The "%s" class is deprecated since Symfony 4.3, use "%s" and type-hint for "%s" instead.', PhpFilesCache::class, PhpFilesAdapter::class, CacheInterface::class), \E_USER_DEPRECATED);`
...
class PhpFilesCache extends AbstractCache implements PruneableInterface
```[](url)

**Comment by michalkleiner** [comment]
Are we ok just with silencing this when getting the field content?

**Comment by emteknetnz** [comment]
Yes. I've got a PR up, will test on an environment that was throwing the error shortly

**Comment by maxime-rainville** [comment]
Merged the PR as a stop gap. But it doesn't address the fundamental issue.

I've added some ACs. We can address this issue properly post release.

**Comment by emteknetnz** [comment]
Can close this now - we're doing work to use new Symfony cache classes in https://github.com/silverstripe/silverstripe-framework/pull/10478
