### ISSUE TITLE
`SearchableService::isSearchable` incorrectly assumes return type of `canView`

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-fulltextsearch#304]
[This method](https://github.com/silverstripe/silverstripe-fulltextsearch/blob/3/src/Search/Services/SearchableService.php#L127) type-hints a boolean, but also returns the value of `DataObject::canView` which is a tri-state. 

Either the tri-state should be dealt with, or the value should be casted.

**Comment by GuySartorelli** [comment]
There is discussion in silverstripe/silverstripe-framework#10184 as to whether `DataObject::canView` is actually a tri-state - but nevertheless it seems like casting the returned value here to a boolean will be prudent.

**Comment by emteknetnz** [comment]
Closing issue as linked PR has been merged
