### ISSUE TITLE
Solr_Reindex build task doesn't work in dev mode in 3.9.0

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-fulltextsearch#308]
From 3.9.0 the Solr_Reindex build task doesn't work in dev mode. With `verbose=1` I can see all of the processes that should get run, but there is no output from any of them. The solr index doesn't get updated at all.

In test mode the correct queued jobs are created, and running them does update the solr index.

**Comment by michalkleiner** [comment]
Thanks for troubleshooting this!

Do you know/have you found what changed that this stopped working?

**Comment by GuySartorelli** [comment]
@michalkleiner In 3.9.0 a change was made to allow symfony/process `^4`, and part of the change included changing the command from being passed as a string to being passed as an array (see #301). Passing the string worked fine (with process 3.x) but it seems (and this is just based on the error output I was seeing) like there is some step if the command is passed as an array to confirm that the first item in the array is a valid executable.

**Comment by michalkleiner** [comment]
Thanks for looking into it further, @GuySartorelli. I'm under the impression you did what you could and I would say that's more than enough here. You're doing great work lately, keep it up!
