### ISSUE TITLE
4.11.0-beta1 PHP 8.1 - Deprecation issue in solr-php-client

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-fulltextsearch#323]
`error-log.NOTICE: E_DEPRECATED: http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated {"code":8192,"message":"http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated","file":"/sites/<mysite>/releases/20220506003258/vendor/silverstripe/solr-php-client/Apache/Solr/Service.php","line":312} []`

Happened when searching for content on a page I just created

We use a forked version of solr-php-client, so update that (I cannot create new issues on that module so created on this module instead) - https://github.com/silverstripe/solr-php-client

### PRs
- https://github.com/silverstripe/solr-php-client/pull/2

**Comment by GuySartorelli** [comment]
PR merged and new patch version released. Closing this issue.
