### ISSUE TITLE
4.11.0-beta2 PHP 8.1 - Changes in content are not reflected in search results

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-fulltextsearch#324]
The default pages (home, about, contact) are found in search results, but new pages or changes to content are not reflected in search results.

If changing content that is _not_ in an elemental block, the FullTextSearch Update Job message just says "[2022-05-16 14:43:05][INFO] All batched updates complete. Queuing commit job" after completion. The commit is created and runs fine, but the new content does not appear in search results.

If changing content that _is_ in an elemental block, or if running a full reindex, the output is a lot more verbose. I will include this in a comment below.

### PRs
- https://github.com/silverstripe/silverstripe-fulltextsearch/pull/278
- https://github.com/dnadesign/silverstripe-elemental-userforms/pull/61

**Comment by emteknetnz** [comment]
Based on the stack trace the error comes from here https://github.com/silverstripe/silverstripe-framework/blob/4/src/Control/RequestHandler.php#L575

Triggered from here - https://github.com/dnadesign/silverstripe-elemental-userforms/blob/3.2/src/Model/ElementForm.php#L43

**Comment by emteknetnz** [comment]
> If changing content that is not in an elemental block, the FullTextSearch Update Job message just says "[2022-05-16 14:43:05][INFO] All batched updates complete. Queuing commit job" after completion. The commit is created and runs fine, but the new content does not appear in search results.

I tried running `/dev/tasks/Solr_Configure`, which was something I forgot to do on deployment.  I'm not sure if it made a difference or not since it's likely it was previously run on the environment for the for the 4.10 release.  Content I added to a new page did show up after several minutes, and I did NOT run /dev/tasks/Solr_Reindex

**Comment by GuySartorelli** [comment]
Did you run configure before or after making the changes to content? If after, it's possible that reloading the core did the trick - but we shouldn't accept that as a solution.
If it was _before_ making changes, and then the changes got correctly indexed and you didn't need to run configure to see results, then that is probably okay - as long as it works for elemental block content as well.

**Comment by emteknetnz** [comment]
Ran it after making content changes.

**Comment by GuySartorelli** [comment]
#278 seems relevant

**Comment by GuySartorelli** [comment]
PRs merged. Closing this issue.
