### ISSUE TITLE
BUG no support for obsolete indexes

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-fulltextsearch#48]
If `SearchUpdateProcessor::process` is called with a dirty record marked against an index that no longer exists, then it will fail on line 58 of SearchUpdateProcessor.

``` php
if (!$indexes[$index]->variantStateExcluded($state)) { // since $indexes[$index] is null
```

This only comes up when running a queued job that has been queued against an obsolete codebase.

I suggest that Solr_Reindex flushes all queued search update tasks, since it doesn't make sense to continue running those tasks against an instance if this work will be repeated.

**Comment by emteknetnz** [comment]
Not sure if this is still an issue, haven't heard any reports of this happening and it really does seem like an edge case with workarounds available e.g. delete and recreate the queuedjob

I'll close this issue, though feel free to re-open with a pull-request if you feel it needs fixing.  Cheers.

**Comment by tractorcow** [comment]
Sounds fair to me. :D
