### ISSUE TITLE
Example is incorrect

### ISSUE THREAD

**Issue by jason-zz** [silverstripe/silverstripe-fulltextsearch#55]
while setting up this module, some issue with the Page class and Title column.

when I set weighting for Title and Content, Solr returned error saying column not found.

In MyIndex.php, Class should be SiteTree not Page ( Title and Content are in SiteTree table.)

```
    $this->addClass('SiteTree');
    $this->addFulltextField('Title');
    $this->addFulltextField('Content');
```

After changing to SiteTree, weighting is working. 

Document should be updated

**Comment by chillu** [comment]
Did you follow the "Configuring boosts on fields" part of `docs/en/Solr.md`? I think the "field not found" error doesn't come from `SiteTree` vs. `Page`, but rather the fact that the fulltextsearch automatically prefixes the property names. So in case you're using boosting, the correct names should be `SiteTree_Title` and `SiteTree_Content` (or `Page_` if you've configured the index with that class instead)

**Comment by RantyDave** [comment]
I couldn't get it working at all until I changed "Page" to "SiteTree".

**Comment by robbieaverill** [comment]
@jason-zz @RantyDave would you be willing to submit a pull request to update the docs if you don't feel they're accurate?

**Comment by dhensby** [comment]
Nothing for 3 years and I'd have expected a lot more feedback on this if it were a fundamental problem with docs
