### ISSUE TITLE
Removing Queued Jobs module reduces functionality to almost nothing

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/silverstripe-fulltextsearch#84]
Removing the QueuedJobs module from your site means that you can only do a small-sized index ie <10 pages. This is almost the same as not functioning for a majority of sites. 

Two courses of action could help this. One, we highly recommend (and make obvious that we recommend) that QueuedJobs be installed for best performance of the module. Two, we remove the part of the module that allows it to function without QueuedJobs. and upgrade the major version of the module.

**Comment by assertchris** [comment]
I'm keen for depending on QueuedJobs and bumping the major version. We shouldn't allow the effective operation of modules to depend on a browser tab staying open long enough, or PHP taking long enough to time out...

**Comment by tractorcow** [comment]
I suggest adding a composer suggest; Since queuedjobs is only one such solution to this problem. Another is the messagequeue module.

**Comment by assertchris** [comment]
Is the queue-able re-index solution made compatible with any other queue module? I agree we should support as many approaches as we reasonably can. I hope we can do that without restricting the size of the queue that can be run without a queue module...

**Comment by madmatt** [comment]
Does it really mean you can only reindex small sites? You don't need queuedjobs, you can run `Solr_Configure` and `Solr_Reindex` from the cmd-line until the cows come home, the timelimit runs forever (well, long enough for me to index 10,000 SiteTree objects and 30GB of files anyway), and I don't get any memory issues with that.

Then, without queuedjobs, my understanding is the index is kept up-to-date automatically - so when you publish a SiteTree object, it will immediately push the index update to Solr. If Solr isn't responding, that's lost I presume whereas queuedjobs might retry the job a few times, but there's no other differences that I'm aware of. Am I missing something?

**Comment by tractorcow** [comment]
@madmatt is mostly right. I wouldn't trust a large index without it though, but there's no reason that a patient person with a personal site wouldn't be able to do it.

**Comment by robbieaverill** [comment]
Fixed with #212
